import { Router } from 'express';
import multer from 'multer';
import { body } from 'express-validator';
import { authenticate, optionalAuth } from '../middleware/authMiddleware.js';
import { requireAdmin } from '../middleware/adminMiddleware.js';
import { validate } from '../middleware/validationMiddleware.js';
import { asyncHandler } from '../utils/responseHandler.js';
import * as c from '../controllers/productController.js';
const router = Router();
const upload = multer({ storage: multer.memoryStorage(), limits: { fileSize: 5 * 1024 * 1024 } });
router.get('/', optionalAuth, asyncHandler(c.listProducts));
router.get('/search', asyncHandler(c.searchProducts));
router.get('/featured', asyncHandler(c.featuredProducts));
router.get('/bestsellers', asyncHandler(c.bestsellerProducts));
router.get('/category/:categoryId', asyncHandler(c.productsByCategory));
router.get('/:id', asyncHandler(c.getProduct));
router.post('/', authenticate, requireAdmin, [body('name').notEmpty(), body('price').isNumeric()], validate, asyncHandler(c.createProduct));
router.put('/:id', authenticate, requireAdmin, asyncHandler(c.updateProduct));
router.delete('/:id', authenticate, requireAdmin, asyncHandler(c.deleteProduct));
router.post('/upload/image', authenticate, requireAdmin, upload.single('image'), asyncHandler(c.uploadProductImage));
export default router;
