// lib/core/constants/dummy_data.dart
// Complete dummy product database for MOSPL

class DummyData {
  static List<Map<String, dynamic>> get categories => [
    {
      'id': 'cat_jackets',
      'name': 'Leather Jackets',
      'description': 'Premium genuine leather jackets for men and women',
      'imageUrl': 'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=400',
      'icon': '🧥',
      'productCount': 12,
      'sortOrder': 1,
      'isActive': true,
      'slug': 'leather-jackets',
    },
    {
      'id': 'cat_bags',
      'name': 'Leather Bags',
      'description': 'Handcrafted leather bags for every occasion',
      'imageUrl': 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=400',
      'icon': '👜',
      'productCount': 15,
      'sortOrder': 2,
      'isActive': true,
      'slug': 'leather-bags',
    },
    {
      'id': 'cat_wallets',
      'name': 'Wallets',
      'description': 'Slim and classic leather wallets',
      'imageUrl': 'https://images.unsplash.com/photo-1627123424574-724758594e93?w=400',
      'icon': '👛',
      'productCount': 14,
      'sortOrder': 3,
      'isActive': true,
      'slug': 'wallets',
    },
    {
      'id': 'cat_belts',
      'name': 'Belts',
      'description': 'Genuine leather belts with premium buckles',
      'imageUrl': 'https://images.unsplash.com/photo-1624222247344-550fb60583dc?w=400',
      'icon': '🪢',
      'productCount': 12,
      'sortOrder': 4,
      'isActive': true,
      'slug': 'belts',
    },
    {
      'id': 'cat_shoes',
      'name': 'Shoes',
      'description': 'Handcrafted leather shoes and boots',
      'imageUrl': 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400',
      'icon': '👞',
      'productCount': 13,
      'sortOrder': 5,
      'isActive': true,
      'slug': 'shoes',
    },
    {
      'id': 'cat_watches',
      'name': 'Watches',
      'description': 'Premium watches with genuine leather straps',
      'imageUrl': 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400',
      'icon': '⌚',
      'productCount': 10,
      'sortOrder': 6,
      'isActive': true,
      'slug': 'watches',
    },
    {
      'id': 'cat_travel_bags',
      'name': 'Travel Bags',
      'description': 'Durable leather travel bags and duffels',
      'imageUrl': 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400',
      'icon': '🧳',
      'productCount': 10,
      'sortOrder': 7,
      'isActive': true,
      'slug': 'travel-bags',
    },
    {
      'id': 'cat_office_bags',
      'name': 'Office Bags',
      'description': 'Professional leather laptop bags and briefcases',
      'imageUrl': 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400',
      'icon': '💼',
      'productCount': 11,
      'sortOrder': 8,
      'isActive': true,
      'slug': 'office-bags',
    },
    {
      'id': 'cat_accessories',
      'name': 'Accessories',
      'description': 'Leather keychains, cardholders and more',
      'imageUrl': 'https://images.unsplash.com/photo-1582561424760-0321d75e81fa?w=400',
      'icon': '🔑',
      'productCount': 12,
      'sortOrder': 9,
      'isActive': true,
      'slug': 'accessories',
    },
    {
      'id': 'cat_premium',
      'name': 'Premium Collections',
      'description': 'Exclusive limited edition leather masterpieces',
      'imageUrl': 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=400',
      'icon': '👑',
      'productCount': 8,
      'sortOrder': 10,
      'isActive': true,
      'slug': 'premium-collections',
    },
  ];

  static List<Map<String, dynamic>> get products => [
    // ==================== LEATHER JACKETS ====================
    {
      'id': 'prod_j001',
      'name': 'Classic Biker Leather Jacket',
      'shortDescription': 'Rugged full-grain leather biker jacket with asymmetric zipper',
      'longDescription': 'Crafted from premium full-grain cowhide leather, this biker jacket exudes timeless masculinity. The asymmetric front zipper, quilted shoulder panels, and multiple zip pockets make it a functional fashion statement. The supple interior lining ensures all-day comfort while the heavy-duty hardware adds to the rugged aesthetic. Perfect for motorcyclists and fashion-forward individuals alike.',
      'categoryId': 'cat_jackets',
      'categoryName': 'Leather Jackets',
      'originalPrice': 8999,
      'offerPrice': 6999,
      'discountPercentage': 22,
      'images': [
        'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=600',
        'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=600',
        'https://images.unsplash.com/photo-1542319630-6c5e8b0b8b8b?w=600',
      ],
      'rating': 4.6,
      'reviewCount': 234,
      'stockCount': 45,
      'availableColors': ['Black', 'Dark Brown', 'Cognac'],
      'availableSizes': ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
      'brand': 'MOSPL',
      'sku': 'MSP-JKT-001',
      'deliveryInfo': {
        'freeDelivery': true,
        'standardDays': 5,
        'expressDays': 2,
        'expressCharge': 199,
      },
      'tags': ['biker', 'jacket', 'leather', 'men', 'premium'],
      'isFeatured': true,
      'isNewArrival': false,
      'isBestSeller': true,
      'isTrending': true,
      'specifications': {
        'Material': 'Full-Grain Cowhide Leather',
        'Lining': 'Satin Polyester',
        'Closure': 'YKK Asymmetric Zipper',
        'Pockets': '4 Exterior, 2 Interior',
        'Weight': '1.8 kg',
        'Origin': 'Made in India',
      },
    },
    {
      'id': 'prod_j002',
      'name': 'Slim Fit Café Racer Jacket',
      'shortDescription': 'Sleek café racer style jacket in premium napa leather',
      'longDescription': 'The epitome of understated cool, this café racer jacket is tailored from buttery-soft napa leather. Its minimalist design with band collar and front zip creates a clean silhouette that transitions effortlessly from casual to smart-casual. The slim fit cuts a flattering profile while the stretch lining allows full freedom of movement.',
      'categoryId': 'cat_jackets',
      'categoryName': 'Leather Jackets',
      'originalPrice': 7499,
      'offerPrice': 5999,
      'discountPercentage': 20,
      'images': [
        'https://images.unsplash.com/photo-1520975954732-35dd22299614?w=600',
        'https://images.unsplash.com/photo-1559478831-8da5fda4e9c4?w=600',
      ],
      'rating': 4.4,
      'reviewCount': 187,
      'stockCount': 32,
      'availableColors': ['Black', 'Navy', 'Burgundy'],
      'availableSizes': ['S', 'M', 'L', 'XL', 'XXL'],
      'brand': 'MOSPL',
      'sku': 'MSP-JKT-002',
      'deliveryInfo': {'freeDelivery': true, 'standardDays': 5, 'expressDays': 2, 'expressCharge': 199},
      'tags': ['cafe racer', 'slim fit', 'leather', 'men'],
      'isFeatured': false,
      'isNewArrival': true,
      'isBestSeller': false,
      'isTrending': true,
      'specifications': {'Material': 'Napa Leather', 'Lining': 'Viscose', 'Closure': 'Front Zip', 'Collar': 'Band Collar', 'Weight': '1.5 kg', 'Origin': 'Made in India'},
    },
    {
      'id': 'prod_j003',
      'name': 'Women\'s Belted Leather Trench',
      'shortDescription': 'Elegant women\'s belted leather trench coat in cognac',
      'longDescription': 'A sophisticated fusion of classic trench silhouette and premium leather craftsmanship. This belted beauty features a double-breasted front, wide lapels, and a waist-defining belt that creates an hourglass silhouette. The rich cognac leather develops a beautiful patina over time, making it a forever investment piece.',
      'categoryId': 'cat_jackets',
      'categoryName': 'Leather Jackets',
      'originalPrice': 12999,
      'offerPrice': 9999,
      'discountPercentage': 23,
      'images': [
        'https://images.unsplash.com/photo-1594938298603-a8ffa3e82fc1?w=600',
        'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600',
      ],
      'rating': 4.8,
      'reviewCount': 95,
      'stockCount': 18,
      'availableColors': ['Cognac', 'Black', 'Camel'],
      'availableSizes': ['XS', 'S', 'M', 'L', 'XL'],
      'brand': 'MOSPL',
      'sku': 'MSP-JKT-003',
      'deliveryInfo': {'freeDelivery': true, 'standardDays': 5, 'expressDays': 2, 'expressCharge': 199},
      'tags': ['women', 'trench', 'elegant', 'leather', 'premium'],
      'isFeatured': true,
      'isNewArrival': true,
      'isBestSeller': false,
      'isTrending': false,
      'specifications': {'Material': 'Top-Grain Leather', 'Style': 'Belted Trench', 'Closure': 'Double-Breasted', 'Belt': 'Matching Leather Belt', 'Weight': '2.1 kg', 'Origin': 'Made in India'},
    },
    {
      'id': 'prod_j004',
      'name': 'Bomber Leather Flight Jacket',
      'shortDescription': 'Classic bomber jacket with ribbed cuffs and hem in genuine leather',
      'longDescription': 'Inspired by WWII flight jackets, this bomber is crafted from genuine cowhide leather with ribbed wool cuffs, collar, and hem for that authentic aviation look. The satin interior lining features a vintage map print adding to its heritage appeal. Multiple pockets provide practical storage.',
      'categoryId': 'cat_jackets',
      'categoryName': 'Leather Jackets',
      'originalPrice': 9499,
      'offerPrice': 7499,
      'discountPercentage': 21,
      'images': [
        'https://images.unsplash.com/photo-1510945509543-8c2bfc0c5f4b?w=600',
      ],
      'rating': 4.5,
      'reviewCount': 156,
      'stockCount': 28,
      'availableColors': ['Tan', 'Black', 'Dark Green'],
      'availableSizes': ['S', 'M', 'L', 'XL', 'XXL', '3XL'],
      'brand': 'MOSPL',
      'sku': 'MSP-JKT-004',
      'deliveryInfo': {'freeDelivery': true, 'standardDays': 5, 'expressDays': 2, 'expressCharge': 199},
      'tags': ['bomber', 'flight jacket', 'vintage', 'men'],
      'isFeatured': false,
      'isNewArrival': false,
      'isBestSeller': true,
      'isTrending': false,
      'specifications': {'Material': 'Genuine Cowhide', 'Lining': 'Satin with Print', 'Collar': 'Ribbed Wool', 'Cuffs': 'Ribbed Knit', 'Weight': '1.7 kg', 'Origin': 'Made in India'},
    },
    {
      'id': 'prod_j005',
      'name': 'Suede Western Jacket',
      'shortDescription': 'Authentic western-style suede leather jacket with fringe',
      'longDescription': 'Channel your inner cowboy with this authentic suede western jacket. Featuring intricate fringe detailing along the chest and sleeves, flap pockets with snap buttons, and a classic western yoke. The soft suede feels luxurious against the skin while the fringe adds movement and personality.',
      'categoryId': 'cat_jackets',
      'categoryName': 'Leather Jackets',
      'originalPrice': 6999,
      'offerPrice': 5499,
      'discountPercentage': 21,
      'images': [
        'https://images.unsplash.com/photo-1594938298603-a8ffa3e82fc1?w=600',
      ],
      'rating': 4.2,
      'reviewCount': 67,
      'stockCount': 15,
      'availableColors': ['Sand', 'Chestnut', 'Grey'],
      'availableSizes': ['S', 'M', 'L', 'XL'],
      'brand': 'MOSPL',
      'sku': 'MSP-JKT-005',
      'deliveryInfo': {'freeDelivery': true, 'standardDays': 5, 'expressDays': 2, 'expressCharge': 199},
      'tags': ['suede', 'western', 'fringe', 'unisex'],
      'isFeatured': false,
      'isNewArrival': true,
      'isBestSeller': false,
      'isTrending': false,
      'specifications': {'Material': 'Genuine Suede', 'Style': 'Western', 'Closure': 'Snap Buttons', 'Details': 'Fringe', 'Weight': '1.4 kg', 'Origin': 'Made in India'},
    },
    // ==================== LEATHER BAGS ====================
    {
      'id': 'prod_b001',
      'name': 'Heritage Tote Bag',
      'shortDescription': 'Spacious handcrafted full-grain leather tote bag',
      'longDescription': 'The Heritage Tote is our most beloved bag, crafted entirely from vegetable-tanned full-grain leather. The open top design allows easy access to your belongings while the sturdy leather handles and optional shoulder strap offer flexible carrying options. Interior features a zip pocket and two slip pockets. This bag ages beautifully, developing a rich patina that tells your unique story.',
      'categoryId': 'cat_bags',
      'categoryName': 'Leather Bags',
      'originalPrice': 5999,
      'offerPrice': 4499,
      'discountPercentage': 25,
      'images': [
        'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600',
        'https://images.unsplash.com/photo-1590874103328-eac38a683ce7?w=600',
        'https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?w=600',
      ],
      'rating': 4.7,
      'reviewCount': 312,
      'stockCount': 56,
      'availableColors': ['Tan', 'Black', 'Cognac', 'Forest Green'],
      'availableSizes': ['Standard', 'Large'],
      'brand': 'MOSPL',
      'sku': 'MSP-BAG-001',
      'deliveryInfo': {'freeDelivery': true, 'standardDays': 4, 'expressDays': 2, 'expressCharge': 149},
      'tags': ['tote', 'women', 'everyday', 'spacious'],
      'isFeatured': true,
      'isNewArrival': false,
      'isBestSeller': true,
      'isTrending': true,
      'specifications': {'Material': 'Full-Grain Vegetable Tanned Leather', 'Dimensions': '40 x 32 x 12 cm', 'Strap': 'Fixed + Detachable', 'Pockets': '1 Zip + 2 Slip', 'Weight': '0.8 kg', 'Origin': 'Made in India'},
    },
    {
      'id': 'prod_b002',
      'name': 'Mini Crossbody Satchel',
      'shortDescription': 'Compact chic crossbody bag in pebbled leather',
      'longDescription': 'Compact yet surprisingly roomy, this mini satchel in pebbled leather is the perfect everyday companion. The structured silhouette features a magnetic closure flap, adjustable crossbody strap, and interior organization with card slots and phone pocket. The pebbled texture adds subtle interest while being highly scratch-resistant.',
      'categoryId': 'cat_bags',
      'categoryName': 'Leather Bags',
      'originalPrice': 3499,
      'offerPrice': 2799,
      'discountPercentage': 20,
      'images': [
        'https://images.unsplash.com/photo-1590874103328-eac38a683ce7?w=600',
        'https://images.unsplash.com/photo-1575032617751-6ddec2089882?w=600',
      ],
      'rating': 4.5,
      'reviewCount': 198,
      'stockCount': 73,
      'availableColors': ['Black', 'Dusty Rose', 'Ivory', 'Cobalt'],
      'availableSizes': ['Mini', 'Small'],
      'brand': 'MOSPL',
      'sku': 'MSP-BAG-002',
      'deliveryInfo': {'freeDelivery': true, 'standardDays': 4, 'expressDays': 2, 'expressCharge': 149},
      'tags': ['crossbody', 'mini', 'women', 'casual'],
      'isFeatured': false,
      'isNewArrival': true,
      'isBestSeller': false,
      'isTrending': true,
      'specifications': {'Material': 'Pebbled Top-Grain Leather', 'Dimensions': '22 x 17 x 7 cm', 'Strap': 'Adjustable 50-130cm', 'Closure': 'Magnetic Flap', 'Weight': '0.4 kg', 'Origin': 'Made in India'},
    },
    {
      'id': 'prod_b003',
      'name': 'Structured Leather Handbag',
      'shortDescription': 'Executive-style structured handbag with gold hardware',
      'longDescription': 'This impeccably structured handbag channels quiet luxury. Crafted from smooth top-grain leather and finished with gold-tone hardware, it projects an air of polished professionalism. The rigid base keeps your essentials organized, while the single top handle and detachable shoulder strap offer styling versatility.',
      'categoryId': 'cat_bags',
      'categoryName': 'Leather Bags',
      'originalPrice': 6499,
      'offerPrice': 4999,
      'discountPercentage': 23,
      'images': [
        'https://images.unsplash.com/photo-1575032617751-6ddec2089882?w=600',
      ],
      'rating': 4.8,
      'reviewCount': 143,
      'stockCount': 29,
      'availableColors': ['Black', 'Camel', 'Burgundy', 'Navy'],
      'availableSizes': ['Medium', 'Large'],
      'brand': 'MOSPL',
      'sku': 'MSP-BAG-003',
      'deliveryInfo': {'freeDelivery': true, 'standardDays': 4, 'expressDays': 2, 'expressCharge': 149},
      'tags': ['handbag', 'structured', 'office', 'premium'],
      'isFeatured': true,
      'isNewArrival': false,
      'isBestSeller': true,
      'isTrending': false,
      'specifications': {'Material': 'Top-Grain Smooth Leather', 'Hardware': 'Gold-Tone', 'Dimensions': '35 x 26 x 14 cm', 'Closure': 'Top Zip', 'Weight': '0.9 kg', 'Origin': 'Made in India'},
    },
    // ==================== WALLETS ====================
    {
      'id': 'prod_w001',
      'name': 'Slim Bifold Wallet',
      'shortDescription': 'Ultra-slim genuine leather bifold wallet with RFID protection',
      'longDescription': 'Carry the essentials without the bulk. This ultra-slim bifold wallet is crafted from premium full-grain leather and features RFID-blocking technology to keep your cards secure. Eight card slots, two bill compartments, and a clear ID window provide excellent organization in a sleek package. The minimalist profile ensures a flat silhouette in your pocket.',
      'categoryId': 'cat_wallets',
      'categoryName': 'Wallets',
      'originalPrice': 1499,
      'offerPrice': 1199,
      'discountPercentage': 20,
      'images': [
        'https://images.unsplash.com/photo-1627123424574-724758594e93?w=600',
        'https://images.unsplash.com/photo-1615485500704-8e990f9900f7?w=600',
      ],
      'rating': 4.6,
      'reviewCount': 456,
      'stockCount': 120,
      'availableColors': ['Black', 'Dark Brown', 'Tan', 'Navy'],
      'availableSizes': ['Standard'],
      'brand': 'MOSPL',
      'sku': 'MSP-WLT-001',
      'deliveryInfo': {'freeDelivery': false, 'standardDays': 4, 'standardCharge': 49, 'expressDays': 2, 'expressCharge': 99},
      'tags': ['wallet', 'slim', 'RFID', 'men', 'minimalist'],
      'isFeatured': false,
      'isNewArrival': false,
      'isBestSeller': true,
      'isTrending': true,
      'specifications': {'Material': 'Full-Grain Leather', 'RFID': 'Yes - Protected', 'Card Slots': '8', 'Bill Compartments': '2', 'ID Window': '1 Clear', 'Dimensions': '11 x 8.5 x 1 cm', 'Weight': '65 g'},
    },
    {
      'id': 'prod_w002',
      'name': 'Long Envelope Clutch Wallet',
      'shortDescription': 'Women\'s elegant long wallet with multiple card slots',
      'longDescription': 'An elegant organizational masterpiece designed for the modern woman. This long envelope wallet features 12 card slots, 3 bill compartments, a zip coin pocket, and a checkbook holder. The exterior button closure and contrasting stitching add a refined finishing touch. Large enough to hold your phone too.',
      'categoryId': 'cat_wallets',
      'categoryName': 'Wallets',
      'originalPrice': 1999,
      'offerPrice': 1599,
      'discountPercentage': 20,
      'images': [
        'https://images.unsplash.com/photo-1615485500704-8e990f9900f7?w=600',
      ],
      'rating': 4.5,
      'reviewCount': 234,
      'stockCount': 85,
      'availableColors': ['Rose Gold', 'Black', 'Burgundy', 'Camel'],
      'availableSizes': ['Standard'],
      'brand': 'MOSPL',
      'sku': 'MSP-WLT-002',
      'deliveryInfo': {'freeDelivery': false, 'standardDays': 4, 'standardCharge': 49, 'expressDays': 2, 'expressCharge': 99},
      'tags': ['wallet', 'women', 'long', 'clutch', 'organizer'],
      'isFeatured': false,
      'isNewArrival': true,
      'isBestSeller': false,
      'isTrending': true,
      'specifications': {'Material': 'Genuine Leather', 'Card Slots': '12', 'Coin Pocket': 'Zip', 'Bill Slots': '3', 'Dimensions': '19 x 9.5 x 2 cm', 'Weight': '120 g'},
    },
    {
      'id': 'prod_w003',
      'name': 'Vintage Trifold Wallet',
      'shortDescription': 'Classic trifold design in aged vintage leather',
      'longDescription': 'Inspired by vintage wallets that last generations, this trifold is crafted from hand-aged leather that has been treated to develop a beautiful rustic patina right out of the box. The trifold design maximizes organization with 6 card slots, 2 currency pockets, a large zipper coin compartment, and 2 transparent ID windows.',
      'categoryId': 'cat_wallets',
      'categoryName': 'Wallets',
      'originalPrice': 1299,
      'offerPrice': 999,
      'discountPercentage': 23,
      'images': [
        'https://images.unsplash.com/photo-1605296830714-7b38c2b8bd8c?w=600',
      ],
      'rating': 4.3,
      'reviewCount': 178,
      'stockCount': 95,
      'availableColors': ['Vintage Brown', 'Dark Tan', 'Mahogany'],
      'availableSizes': ['Standard'],
      'brand': 'MOSPL',
      'sku': 'MSP-WLT-003',
      'deliveryInfo': {'freeDelivery': false, 'standardDays': 4, 'standardCharge': 49, 'expressDays': 2, 'expressCharge': 99},
      'tags': ['wallet', 'vintage', 'trifold', 'men', 'classic'],
      'isFeatured': false,
      'isNewArrival': false,
      'isBestSeller': false,
      'isTrending': false,
      'specifications': {'Material': 'Hand-Aged Leather', 'Card Slots': '6', 'ID Windows': '2', 'Coin Pocket': 'Zipper', 'Dimensions': '10 x 9 x 2.5 cm', 'Weight': '95 g'},
    },
    // ==================== BELTS ====================
    {
      'id': 'prod_belt001',
      'name': 'Classic Formal Leather Belt',
      'shortDescription': 'Premium full-grain leather dress belt with polished buckle',
      'longDescription': 'The quintessential dress belt for the sophisticated professional. Crafted from a single piece of full-grain leather with a smooth, polished surface, this belt features a classic single-prong nickel-free buckle with subtle brushed finish. Ideal for pairing with formal trousers, chinos, and business attire. Available in a range of waist sizes.',
      'categoryId': 'cat_belts',
      'categoryName': 'Belts',
      'originalPrice': 1499,
      'offerPrice': 1199,
      'discountPercentage': 20,
      'images': [
        'https://images.unsplash.com/photo-1624222247344-550fb60583dc?w=600',
      ],
      'rating': 4.7,
      'reviewCount': 389,
      'stockCount': 200,
      'availableColors': ['Black', 'Dark Brown', 'Tan'],
      'availableSizes': ['28', '30', '32', '34', '36', '38', '40', '42', '44'],
      'brand': 'MOSPL',
      'sku': 'MSP-BLT-001',
      'deliveryInfo': {'freeDelivery': false, 'standardDays': 4, 'standardCharge': 49, 'expressDays': 2, 'expressCharge': 99},
      'tags': ['belt', 'formal', 'dress', 'men', 'classic'],
      'isFeatured': false,
      'isNewArrival': false,
      'isBestSeller': true,
      'isTrending': false,
      'specifications': {'Material': 'Full-Grain Leather', 'Width': '3.5 cm', 'Buckle': 'Brushed Nickel-Free', 'Holes': '5 standard + custom', 'Thickness': '4mm'},
    },
    {
      'id': 'prod_belt002',
      'name': 'Woven Leather Casual Belt',
      'shortDescription': 'Stylish woven leather belt perfect for casual and smart-casual',
      'longDescription': 'A unique hand-woven leather belt that adds texture and character to any outfit. Each strand of leather is individually dyed and woven together for a rich, multidimensional look. The hardy pin buckle and tip are finished in antique brass. Works beautifully with jeans, chinos, and casual trousers.',
      'categoryId': 'cat_belts',
      'categoryName': 'Belts',
      'originalPrice': 1799,
      'offerPrice': 1399,
      'discountPercentage': 22,
      'images': [
        'https://images.unsplash.com/photo-1624222247344-550fb60583dc?w=600',
      ],
      'rating': 4.4,
      'reviewCount': 156,
      'stockCount': 150,
      'availableColors': ['Tan/Cognac', 'Black/Grey', 'Brown/Camel'],
      'availableSizes': ['28', '30', '32', '34', '36', '38', '40'],
      'brand': 'MOSPL',
      'sku': 'MSP-BLT-002',
      'deliveryInfo': {'freeDelivery': false, 'standardDays': 4, 'standardCharge': 49, 'expressDays': 2, 'expressCharge': 99},
      'tags': ['belt', 'woven', 'casual', 'men', 'textured'],
      'isFeatured': false,
      'isNewArrival': true,
      'isBestSeller': false,
      'isTrending': true,
      'specifications': {'Material': 'Hand-Woven Leather Strands', 'Width': '3 cm', 'Buckle': 'Antique Brass', 'Style': 'Woven/Braided'},
    },
    // ==================== SHOES ====================
    {
      'id': 'prod_sh001',
      'name': 'Oxford Brogue Leather Shoes',
      'shortDescription': 'Handcrafted Oxford brogues in full-grain leather',
      'longDescription': 'These full-grain leather Oxford brogues are a masterclass in traditional shoemaking. Featuring intricate brogue detailing including perforations, medallion toe, and wing tip, they are constructed using the Goodyear welt method for superior durability and resolability. The leather sole and heel provide a satisfying click with every confident step. Ideal for formal occasions and business wear.',
      'categoryId': 'cat_shoes',
      'categoryName': 'Shoes',
      'originalPrice': 5999,
      'offerPrice': 4799,
      'discountPercentage': 20,
      'images': [
        'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600',
        'https://images.unsplash.com/photo-1514373941175-0a141072bbc8?w=600',
      ],
      'rating': 4.7,
      'reviewCount': 267,
      'stockCount': 48,
      'availableColors': ['Oxford Tan', 'Dark Brown', 'Black'],
      'availableSizes': ['39', '40', '41', '42', '43', '44', '45', '46'],
      'brand': 'MOSPL',
      'sku': 'MSP-SHO-001',
      'deliveryInfo': {'freeDelivery': true, 'standardDays': 5, 'expressDays': 2, 'expressCharge': 149},
      'tags': ['shoes', 'oxford', 'brogue', 'formal', 'men'],
      'isFeatured': true,
      'isNewArrival': false,
      'isBestSeller': true,
      'isTrending': false,
      'specifications': {'Material': 'Full-Grain Leather Upper', 'Construction': 'Goodyear Welt', 'Sole': 'Leather', 'Insole': 'Cushioned Leather', 'Lining': 'Leather', 'Origin': 'Made in India'},
    },
    {
      'id': 'prod_sh002',
      'name': 'Chelsea Boots',
      'shortDescription': 'Sleek pull-on Chelsea boots in smooth leather',
      'longDescription': 'The Chelsea boot is a timeless staple that bridges casual and formal effortlessly. Our version in smooth top-grain leather features the signature elasticated side panels, pull-on tab, and a stacked leather heel. The rounded toe and clean silhouette make it infinitely wearable — dress up with tailored trousers or down with dark denim.',
      'categoryId': 'cat_shoes',
      'categoryName': 'Shoes',
      'originalPrice': 4999,
      'offerPrice': 3999,
      'discountPercentage': 20,
      'images': [
        'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=600',
      ],
      'rating': 4.6,
      'reviewCount': 198,
      'stockCount': 62,
      'availableColors': ['Black', 'Cognac', 'Dark Brown'],
      'availableSizes': ['38', '39', '40', '41', '42', '43', '44', '45'],
      'brand': 'MOSPL',
      'sku': 'MSP-SHO-002',
      'deliveryInfo': {'freeDelivery': true, 'standardDays': 5, 'expressDays': 2, 'expressCharge': 149},
      'tags': ['shoes', 'chelsea', 'boots', 'unisex', 'versatile'],
      'isFeatured': false,
      'isNewArrival': false,
      'isBestSeller': true,
      'isTrending': true,
      'specifications': {'Material': 'Top-Grain Smooth Leather', 'Closure': 'Elastic Side + Pull Tab', 'Sole': 'Rubber with Leather Overlay', 'Heel': 'Stacked Leather', 'Toe': 'Rounded', 'Origin': 'Made in India'},
    },
    {
      'id': 'prod_sh003',
      'name': 'Loafer with Tassels',
      'shortDescription': 'Classic tassel loafers in butter-soft leather',
      'longDescription': 'Step into effortless elegance with these classic tassel loafers. Crafted from butter-soft calfskin leather, the slip-on design features decorative leather tassels, a penny-loafer silhouette, and a low leather heel. The genuine leather insole conforms to the shape of your foot for a personalized fit over time. Perfect for both office and weekend wear.',
      'categoryId': 'cat_shoes',
      'categoryName': 'Shoes',
      'originalPrice': 4499,
      'offerPrice': 3599,
      'discountPercentage': 20,
      'images': [
        'https://images.unsplash.com/photo-1560343090-f0409e92791a?w=600',
      ],
      'rating': 4.4,
      'reviewCount': 134,
      'stockCount': 55,
      'availableColors': ['Tan', 'Black', 'Navy Suede'],
      'availableSizes': ['39', '40', '41', '42', '43', '44', '45'],
      'brand': 'MOSPL',
      'sku': 'MSP-SHO-003',
      'deliveryInfo': {'freeDelivery': true, 'standardDays': 5, 'expressDays': 2, 'expressCharge': 149},
      'tags': ['shoes', 'loafer', 'tassel', 'men', 'casual-formal'],
      'isFeatured': false,
      'isNewArrival': true,
      'isBestSeller': false,
      'isTrending': false,
      'specifications': {'Material': 'Calfskin Leather', 'Style': 'Tassel Loafer', 'Sole': 'Leather', 'Heel': '2.5 cm', 'Insole': 'Leather Cushioned'},
    },
    // ==================== WATCHES ====================
    {
      'id': 'prod_wt001',
      'name': 'Heritage Chronograph Watch',
      'shortDescription': 'Swiss movement chronograph with genuine leather strap',
      'longDescription': 'A tribute to classic watchmaking heritage, this chronograph timepiece features a Japanese quartz movement, sapphire crystal glass, and a 42mm stainless steel case. The genuine dark brown leather strap with contrast stitching ages beautifully, and the water-resistance rating of 50m ensures everyday durability. The white dial with gold-tone indices radiates vintage sophistication.',
      'categoryId': 'cat_watches',
      'categoryName': 'Watches',
      'originalPrice': 8999,
      'offerPrice': 6999,
      'discountPercentage': 22,
      'images': [
        'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600',
        'https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=600',
      ],
      'rating': 4.8,
      'reviewCount': 189,
      'stockCount': 34,
      'availableColors': ['Brown Strap/White Dial', 'Black Strap/Black Dial', 'Tan Strap/Cream Dial'],
      'availableSizes': ['42mm'],
      'brand': 'MOSPL',
      'sku': 'MSP-WTC-001',
      'deliveryInfo': {'freeDelivery': true, 'standardDays': 5, 'expressDays': 2, 'expressCharge': 149},
      'tags': ['watch', 'chronograph', 'leather strap', 'men', 'vintage'],
      'isFeatured': true,
      'isNewArrival': false,
      'isBestSeller': true,
      'isTrending': true,
      'specifications': {'Movement': 'Japanese Quartz', 'Case': '42mm Stainless Steel', 'Glass': 'Sapphire Crystal', 'Water Resistance': '50m', 'Strap': 'Genuine Leather 22mm', 'Battery Life': '2 years'},
    },
    {
      'id': 'prod_wt002',
      'name': 'Minimalist Dress Watch',
      'shortDescription': 'Ultra-slim dress watch with interchangeable leather straps',
      'longDescription': 'For those who believe less is more, this ultra-slim dress watch (6.5mm case) is the pinnacle of minimalist design. The clean white or black dial has no date window — just hours, minutes, and a slim seconds hand for pure elegance. Comes with two interchangeable genuine leather straps (black and tan) for versatile styling.',
      'categoryId': 'cat_watches',
      'categoryName': 'Watches',
      'originalPrice': 5999,
      'offerPrice': 4799,
      'discountPercentage': 20,
      'images': [
        'https://images.unsplash.com/photo-1526045612212-70caf35c14df?w=600',
      ],
      'rating': 4.6,
      'reviewCount': 145,
      'stockCount': 48,
      'availableColors': ['White Dial', 'Black Dial', 'Cream Dial'],
      'availableSizes': ['38mm', '40mm'],
      'brand': 'MOSPL',
      'sku': 'MSP-WTC-002',
      'deliveryInfo': {'freeDelivery': true, 'standardDays': 5, 'expressDays': 2, 'expressCharge': 149},
      'tags': ['watch', 'minimalist', 'dress', 'unisex', 'slim'],
      'isFeatured': false,
      'isNewArrival': true,
      'isBestSeller': false,
      'isTrending': true,
      'specifications': {'Movement': 'Swiss Quartz', 'Case Thickness': '6.5mm', 'Glass': 'Mineral', 'Straps': '2 Interchangeable', 'Strap Width': '20mm', 'Water Resistance': '30m'},
    },
    // ==================== TRAVEL BAGS ====================
    {
      'id': 'prod_tb001',
      'name': 'Weekender Duffel Bag',
      'shortDescription': 'Rugged leather weekender duffel for short getaways',
      'longDescription': 'Pack light and travel in style with this spacious leather weekender duffel. The waxed canvas and leather combination creates a bag that is simultaneously tough and refined. The main compartment easily holds 3-4 days worth of clothes, while the exterior zip pocket holds documents and essentials. A separate shoe compartment keeps footwear isolated.',
      'categoryId': 'cat_travel_bags',
      'categoryName': 'Travel Bags',
      'originalPrice': 7999,
      'offerPrice': 6499,
      'discountPercentage': 19,
      'images': [
        'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600',
        'https://images.unsplash.com/photo-1581605405669-f3f2f8b3b1fb?w=600',
      ],
      'rating': 4.7,
      'reviewCount': 167,
      'stockCount': 37,
      'availableColors': ['Brown/Canvas', 'Black/Black', 'Tan/Olive'],
      'availableSizes': ['40L', '55L'],
      'brand': 'MOSPL',
      'sku': 'MSP-TRV-001',
      'deliveryInfo': {'freeDelivery': true, 'standardDays': 5, 'expressDays': 3, 'expressCharge': 249},
      'tags': ['travel', 'duffel', 'weekender', 'men', 'adventure'],
      'isFeatured': true,
      'isNewArrival': false,
      'isBestSeller': true,
      'isTrending': false,
      'specifications': {'Material': 'Waxed Canvas + Leather Trim', 'Capacity': '40L / 55L', 'Pockets': '3 Exterior + 2 Interior', 'Shoe Compartment': 'Yes', 'Carrying Options': 'Duffel Handles + Shoulder Strap', 'Weight': '1.4 kg'},
    },
    {
      'id': 'prod_tb002',
      'name': 'Leather Rolling Carry-On',
      'shortDescription': 'Luxury leather soft-shell rolling carry-on luggage',
      'longDescription': 'Travel in uncompromising luxury with this premium leather soft-shell rolling carry-on. Full-grain leather panels are complemented by polished aluminum spinner wheels, a TSA-approved combination lock, and a telescoping aluminum handle. Meets standard cabin baggage requirements for most airlines. The fully lined interior with mesh divider and tie-down straps keeps clothing wrinkle-free.',
      'categoryId': 'cat_travel_bags',
      'categoryName': 'Travel Bags',
      'originalPrice': 14999,
      'offerPrice': 11999,
      'discountPercentage': 20,
      'images': [
        'https://images.unsplash.com/photo-1565026057447-bc90a3dceb87?w=600',
      ],
      'rating': 4.9,
      'reviewCount': 89,
      'stockCount': 15,
      'availableColors': ['Cognac', 'Black', 'Navy'],
      'availableSizes': ['Cabin (55cm)'],
      'brand': 'MOSPL',
      'sku': 'MSP-TRV-002',
      'deliveryInfo': {'freeDelivery': true, 'standardDays': 7, 'expressDays': 3, 'expressCharge': 399},
      'tags': ['travel', 'luggage', 'carry-on', 'premium', 'luxury'],
      'isFeatured': true,
      'isNewArrival': true,
      'isBestSeller': false,
      'isTrending': true,
      'specifications': {'Material': 'Full-Grain Leather', 'Wheels': 'Dual Spinner 360°', 'Lock': 'TSA Combination', 'Handle': 'Aluminum Telescoping', 'Capacity': '38L', 'Dimensions': '55 x 35 x 20 cm', 'Weight': '3.2 kg'},
    },
    // ==================== OFFICE BAGS ====================
    {
      'id': 'prod_ob001',
      'name': 'Executive Leather Briefcase',
      'shortDescription': 'Classic two-handle executive briefcase in full-grain leather',
      'longDescription': 'Command the boardroom with this classic executive briefcase. Crafted from a single hide of full-grain leather, it features a main compartment with laptop sleeve (fits up to 15.6"), document organizer, and multiple pockets. The traditional two-handle design with a removable shoulder strap offers flexible carrying options. Gold-tone locks add a touch of executive elegance.',
      'categoryId': 'cat_office_bags',
      'categoryName': 'Office Bags',
      'originalPrice': 9999,
      'offerPrice': 7999,
      'discountPercentage': 20,
      'images': [
        'https://images.unsplash.com/photo-1547949003-9792a18a2601?w=600',
        'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600',
      ],
      'rating': 4.8,
      'reviewCount': 198,
      'stockCount': 42,
      'availableColors': ['Dark Brown', 'Black', 'Cognac'],
      'availableSizes': ['Standard (fits 15.6" laptop)'],
      'brand': 'MOSPL',
      'sku': 'MSP-OFF-001',
      'deliveryInfo': {'freeDelivery': true, 'standardDays': 5, 'expressDays': 2, 'expressCharge': 199},
      'tags': ['office', 'briefcase', 'executive', 'laptop', 'men'],
      'isFeatured': true,
      'isNewArrival': false,
      'isBestSeller': true,
      'isTrending': false,
      'specifications': {'Material': 'Full-Grain Leather', 'Laptop Size': 'Up to 15.6"', 'Lock': 'Dual Combination', 'Handles': 'Double Leather Handle', 'Shoulder Strap': 'Detachable', 'Pockets': '5', 'Weight': '1.6 kg'},
    },
    {
      'id': 'prod_ob002',
      'name': 'Leather Laptop Backpack',
      'shortDescription': 'Smart urban leather backpack with anti-theft features',
      'longDescription': 'The modern professional\'s backpack, designed for the urban commute. This leather backpack features a dedicated padded laptop compartment (up to 15.6"), a hidden anti-theft back pocket, USB charging port, and luggage strap for travel. The ergonomic shoulder straps are padded for all-day comfort. Smart organization includes a tablet slot, pen loops, and card holders.',
      'categoryId': 'cat_office_bags',
      'categoryName': 'Office Bags',
      'originalPrice': 6999,
      'offerPrice': 5499,
      'discountPercentage': 21,
      'images': [
        'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600',
      ],
      'rating': 4.7,
      'reviewCount': 289,
      'stockCount': 67,
      'availableColors': ['Black', 'Dark Brown', 'Grey'],
      'availableSizes': ['25L'],
      'brand': 'MOSPL',
      'sku': 'MSP-OFF-002',
      'deliveryInfo': {'freeDelivery': true, 'standardDays': 5, 'expressDays': 2, 'expressCharge': 199},
      'tags': ['backpack', 'laptop', 'office', 'anti-theft', 'men', 'women'],
      'isFeatured': false,
      'isNewArrival': true,
      'isBestSeller': true,
      'isTrending': true,
      'specifications': {'Material': 'Genuine Leather', 'Laptop Size': 'Up to 15.6"', 'Capacity': '25L', 'USB Port': 'Built-in', 'Anti-Theft': 'Hidden Back Pocket', 'Luggage Strap': 'Yes', 'Weight': '1.2 kg'},
    },
    // ==================== ACCESSORIES ====================
    {
      'id': 'prod_acc001',
      'name': 'Premium Leather Keychain Set',
      'shortDescription': 'Set of 3 handcrafted leather keychains in gift box',
      'longDescription': 'A thoughtfully curated gift set of three handcrafted leather keychains in complementary designs. The set includes a classic tag keychain, a folded key fob, and a decorative tassel keychain. Each is crafted from vegetable-tanned leather, hand-stitched with waxed thread, and finished with solid brass hardware. Presented in a premium MOSPL gift box.',
      'categoryId': 'cat_accessories',
      'categoryName': 'Accessories',
      'originalPrice': 799,
      'offerPrice': 599,
      'discountPercentage': 25,
      'images': [
        'https://images.unsplash.com/photo-1582561424760-0321d75e81fa?w=600',
      ],
      'rating': 4.5,
      'reviewCount': 234,
      'stockCount': 150,
      'availableColors': ['Tan', 'Brown', 'Black', 'Mixed Set'],
      'availableSizes': ['Set of 3'],
      'brand': 'MOSPL',
      'sku': 'MSP-ACC-001',
      'deliveryInfo': {'freeDelivery': false, 'standardDays': 3, 'standardCharge': 49, 'expressDays': 1, 'expressCharge': 99},
      'tags': ['keychain', 'gift', 'accessories', 'set', 'unisex'],
      'isFeatured': false,
      'isNewArrival': false,
      'isBestSeller': true,
      'isTrending': false,
      'specifications': {'Material': 'Vegetable-Tanned Leather', 'Hardware': 'Solid Brass', 'Stitching': 'Hand-Stitched Waxed Thread', 'Includes': '3 keychains', 'Packaging': 'Gift Box'},
    },
    {
      'id': 'prod_acc002',
      'name': 'Slim Leather Card Holder',
      'shortDescription': 'Minimalist RFID card holder with quick-access slot',
      'longDescription': 'When you only need your cards, the Slim Card Holder is perfect. Crafted from premium top-grain leather, this ultra-thin card holder (just 5mm) holds up to 6 cards in its tight card slots with RFID-blocking technology. A quick-access front slot lets you retrieve your most-used card with a simple press from the back. Available in 8 colors.',
      'categoryId': 'cat_accessories',
      'categoryName': 'Accessories',
      'originalPrice': 699,
      'offerPrice': 549,
      'discountPercentage': 21,
      'images': [
        'https://images.unsplash.com/photo-1559478831-8da5fda4e9c4?w=600',
      ],
      'rating': 4.6,
      'reviewCount': 312,
      'stockCount': 200,
      'availableColors': ['Black', 'Brown', 'Navy', 'Forest Green', 'Burgundy', 'Tan', 'Grey', 'Red'],
      'availableSizes': ['Standard'],
      'brand': 'MOSPL',
      'sku': 'MSP-ACC-002',
      'deliveryInfo': {'freeDelivery': false, 'standardDays': 3, 'standardCharge': 49, 'expressDays': 1, 'expressCharge': 99},
      'tags': ['card holder', 'wallet', 'RFID', 'minimalist', 'unisex'],
      'isFeatured': false,
      'isNewArrival': true,
      'isBestSeller': true,
      'isTrending': true,
      'specifications': {'Material': 'Top-Grain Leather', 'RFID': 'Blocked', 'Card Capacity': '6', 'Thickness': '5mm', 'Quick-Access': 'Yes'},
    },
    // ==================== PREMIUM COLLECTIONS ====================
    {
      'id': 'prod_prem001',
      'name': 'Exotic Python-Embossed Clutch',
      'shortDescription': 'Limited edition python-embossed leather evening clutch',
      'longDescription': 'From our limited Premium Collection, this evening clutch is crafted from ethically sourced leather embossed with an exotic python pattern for a statement look. The metallic gold turn-lock closure and gold chain strap add opulence. The interior is lined in silk-feel satin with a mirror pocket and card slots. A true collector\'s piece and heirloom accessory.',
      'categoryId': 'cat_premium',
      'categoryName': 'Premium Collections',
      'originalPrice': 9999,
      'offerPrice': 8499,
      'discountPercentage': 15,
      'images': [
        'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=600',
      ],
      'rating': 4.9,
      'reviewCount': 67,
      'stockCount': 12,
      'availableColors': ['Gold Python', 'Black Python', 'Champagne Python'],
      'availableSizes': ['Standard'],
      'brand': 'MOSPL Premium',
      'sku': 'MSP-PREM-001',
      'deliveryInfo': {'freeDelivery': true, 'standardDays': 5, 'expressDays': 2, 'expressCharge': 299},
      'tags': ['premium', 'clutch', 'evening', 'exotic', 'women', 'limited'],
      'isFeatured': true,
      'isNewArrival': true,
      'isBestSeller': false,
      'isTrending': true,
      'specifications': {'Material': 'Python-Embossed Leather', 'Lining': 'Silk Satin', 'Hardware': 'Gold-Tone', 'Closure': 'Turn-Lock', 'Chain': 'Gold 110cm', 'Edition': 'Limited'},
    },
    {
      'id': 'prod_prem002',
      'name': 'Hand-Painted Artisan Bag',
      'shortDescription': 'One-of-a-kind hand-painted leather bag by Indian artisans',
      'longDescription': 'Each bag in this collection is a unique work of art, hand-painted by skilled artisans from Chennai using traditional vegetable-based dyes on vegetable-tanned leather. The folk art motifs celebrate India\'s rich craft heritage. Because each piece is hand-painted, no two are identical. Comes with a certificate of authenticity and the artisan\'s signature on the interior.',
      'categoryId': 'cat_premium',
      'categoryName': 'Premium Collections',
      'originalPrice': 12999,
      'offerPrice': 10999,
      'discountPercentage': 15,
      'images': [
        'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600',
      ],
      'rating': 5.0,
      'reviewCount': 34,
      'stockCount': 8,
      'availableColors': ['Each Piece Unique'],
      'availableSizes': ['Medium'],
      'brand': 'MOSPL Artisan',
      'sku': 'MSP-PREM-002',
      'deliveryInfo': {'freeDelivery': true, 'standardDays': 7, 'expressDays': 3, 'expressCharge': 399},
      'tags': ['artisan', 'hand-painted', 'premium', 'heritage', 'unique', 'India'],
      'isFeatured': true,
      'isNewArrival': true,
      'isBestSeller': false,
      'isTrending': true,
      'specifications': {'Material': 'Vegetable-Tanned Leather', 'Paint': 'Vegetable-Based Dyes', 'Uniqueness': 'Each Piece One-of-a-Kind', 'Certificate': 'Authenticity Certificate Included', 'Origin': 'Chennai, Tamil Nadu'},
    },
  ];

  static List<Map<String, dynamic>> get banners => [
    {
      'id': 'banner_001',
      'title': 'New Arrivals 2024',
      'subtitle': 'Discover Premium Leather Collections',
      'imageUrl': 'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=800',
      'actionUrl': '/products?filter=new_arrival',
      'buttonText': 'Shop Now',
      'isActive': true,
      'sortOrder': 1,
    },
    {
      'id': 'banner_002',
      'title': 'Up to 25% Off',
      'subtitle': 'On Premium Leather Bags & Wallets',
      'imageUrl': 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=800',
      'actionUrl': '/products?filter=on_sale',
      'buttonText': 'Grab Deal',
      'isActive': true,
      'sortOrder': 2,
    },
    {
      'id': 'banner_003',
      'title': 'Artisan Collection',
      'subtitle': 'Handcrafted by Chennai\'s Master Craftsmen',
      'imageUrl': 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=800',
      'actionUrl': '/products?category=cat_premium',
      'buttonText': 'Explore',
      'isActive': true,
      'sortOrder': 3,
    },
    {
      'id': 'banner_004',
      'title': 'Free Shipping',
      'subtitle': 'On All Orders Above ₹999',
      'imageUrl': 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800',
      'actionUrl': '/products',
      'buttonText': 'Shop Now',
      'isActive': true,
      'sortOrder': 4,
    },
  ];

  static List<Map<String, dynamic>> get coupons => [
    {
      'id': 'coup_001',
      'code': 'MOSPL10',
      'title': '10% Off on First Order',
      'description': 'Get 10% off on your first order. Valid for all products.',
      'discountType': 'percentage',
      'discountValue': 10,
      'minOrderValue': 999,
      'maxDiscount': 500,
      'usageLimit': 1000,
      'usedCount': 234,
      'expiryDate': '2024-12-31',
      'isActive': true,
      'applicableCategories': [],
    },
    {
      'id': 'coup_002',
      'code': 'LEATHER500',
      'title': '₹500 Off on Orders Above ₹3999',
      'description': 'Flat ₹500 discount on orders worth ₹3999 or more.',
      'discountType': 'flat',
      'discountValue': 500,
      'minOrderValue': 3999,
      'maxDiscount': 500,
      'usageLimit': 500,
      'usedCount': 89,
      'expiryDate': '2024-12-31',
      'isActive': true,
      'applicableCategories': [],
    },
    {
      'id': 'coup_003',
      'code': 'NEWUSER',
      'title': '15% Off for New Users',
      'description': 'New user exclusive - 15% off up to ₹750',
      'discountType': 'percentage',
      'discountValue': 15,
      'minOrderValue': 1499,
      'maxDiscount': 750,
      'usageLimit': 1,
      'usedCount': 0,
      'expiryDate': '2024-12-31',
      'isActive': true,
      'applicableCategories': [],
    },
  ];

  static List<Map<String, dynamic>> get sampleReviews => [
    {
      'userId': 'user_001',
      'userName': 'Arjun Sharma',
      'rating': 5,
      'title': 'Absolutely Premium Quality!',
      'comment': 'The leather quality is exceptional. I\'ve bought many leather goods but MOSPL truly stands apart. The stitching is flawless and the color is exactly as shown. Will definitely order again!',
      'isVerifiedPurchase': true,
      'helpfulCount': 45,
    },
    {
      'userId': 'user_002',
      'userName': 'Priya Venkatesh',
      'rating': 4,
      'title': 'Great product, slight delay in delivery',
      'comment': 'The bag is beautiful and the leather smell is authentic. Delivery took 6 days instead of 5 but the product itself is worth every rupee. The gift packaging was a lovely touch.',
      'isVerifiedPurchase': true,
      'helpfulCount': 23,
    },
    {
      'userId': 'user_003',
      'userName': 'Rahul Krishnamurthy',
      'rating': 5,
      'title': 'Best leather wallet I\'ve owned',
      'comment': 'Bought the slim bifold for my husband\'s birthday. He absolutely loves it! The RFID protection and the quality of the leather are outstanding. The stitching is perfect and it fits perfectly in his jeans pocket without any bulk.',
      'isVerifiedPurchase': true,
      'helpfulCount': 67,
    },
    {
      'userId': 'user_004',
      'userName': 'Deepika Subramaniam',
      'rating': 5,
      'title': 'Exceeded all expectations',
      'comment': 'Ordered the Heritage Tote and I\'m in love! The leather is so soft and the tan color is gorgeous. It\'s a perfect daily bag - fits my laptop, documents, and everything else. Already getting compliments at office!',
      'isVerifiedPurchase': true,
      'helpfulCount': 89,
    },
  ];
}